### ISSUE TITLE
improve list scroll performance with react-native-optimized-flatlist

### ISSUE THREAD

**Issue by stuller** [AdaAndGrace/today#33]
FlatList is slowwwww to update.  let's see if react-native-optimized-flatlist will speed it up.

https://www.npmjs.com/package/react-native-optimized-flatlist

**Comment by stuller** [comment]
I'm going to grab this one, hopefully it's a quick fix

**Comment by anneswanson** [comment]
I think we're good on this now that you've optimized it. Closing out.
